var RLANG = {
	html: 'HTML',
	video: 'Vidéo',
	image: 'Image',
	table: 'Table',
	link: 'Lien',
	link_insert: 'Insérer un lien...',
	unlink: 'Retirer le lien',
	styles: 'Styles',
	paragraph: 'Paragraphe',
	quote: 'Citation',
	code: 'Code',
	header1: 'Header 1',
	header2: 'Header 2',
	header3: 'Header 3',
	header4: 'Header 4',
	format: 'Format',
	bold:  'Gras',
	italic: 'Italique',
	superscript: 'Superscript',
	strikethrough: 'Surligné',
	fontcolor: 'Couleur de police',
	backcolor: 'Couleur de surlignement',
	removeformat: 'Retirer le formatage',
	cleanstyles: 'Clean styles',
	lists: 'Listes',
	unorderedlist: 'Unordered list',
	orderedlist: 'Ordered list',	
	outdent: 'Outdent',
	indent: 'Indent',
	redo: 'Redo',
	undo: 'Undo',
	cut: 'Cut',
	cancel: 'Annuler',	
	insert: 'Insérer',
	save: 'Sauvegarder',	
	_delete: 'Suprimmer',
	insert_table: 'Insérer un tableau',		
	insert_row_above: 'Add row above',
	insert_row_below: 'Add row below',
	insert_column_left: 'Add column left',
	insert_column_right: 'Add column right',									
	delete_column: 'Delete column',									
	delete_row: 'Delete row',									
	delete_table: 'Delete table',
	Rows: 'Rows',
	Columns: 'Columns',	
	add_head: 'Add head',
	delete_head: 'Delete head',	
	title: 'Title',
	image_view: 'View image',
	image_position: 'Position',
	none: 'none',
	left: 'left',
	right: 'right',
	image_web_link: 'Image web link',
	text: 'Text',
	mailto: 'Email',
	web: 'URL',
	video_html_code: 'Video embed code',
	file: 'Fichier',	
	upload: 'Envoyer',
	download: 'Télécharger',
	choose: 'Sélectionner dans la liste',
	or_choose: 'Ou sélectionner',
	drop_file_here: 'Déposer vos fichiers ici',
	align_left:	'Alignement à gauche',	
	align_center: 'Centrer',
	align_right: 'Alignement à droite',
	align_justify: 'Justifie',
	horizontalrule: 'Horizontal rule',
	fullscreen: 'Plein écran',
	deleted: 'Barré',
	none: 'Aucun',
	anchor: 'Anchor'
};
